### PR TITLE
Add method and add classmethod tag

### PR DESCRIPTION
**Pull request by PeterlitsZo**
Set get_part as a classmethod, and add method `get_parts`

For: #36, #45

### CODE REVIEW

**Comment by PeterlitsZo** [comment]
Well, I will fix it.

**Comment by PeterlitsZo** [comment]
How can I deal with coverage? I think I need some help~

**Comment by PeterlitsZo** [comment]
Do I need to update `tests.py`?

**Comment by PeterlitsZo** [comment]
Looks great! but method `get_part`'s usage changed. If you want to pull this, I think it is better to change version.

**Comment by stefankoegl** [comment]
Thanks for the contribution!

> but method ``get_part``'s usage changed. 

Do you see any case that was valid before but is failing now? It should still be ok to call the classmethod from an instance, right?

**Comment by PeterlitsZo** [comment]
OMG, you are so smart. Right at total!

**Comment by stefankoegl** [comment]
Thanks for your contribution :)

**Pull request merged**
